### ISSUE TITLE
Can't find variable Intl

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-web-site#45]
If I go to http://legislation.openfisca.fr/variables, no interactive widget works, and the console logs the error `Can't find variable Intl`.

**Comment by cbenz** [comment]
Thanks for the report.

I thought that today Intl.js was bundled into all browsers.

http://caniuse.com/#feat=internationalization

May I ask your browser version, just curious.

The fix I imagine is to add a polyfill when it is missing.

**Comment by MattiSG** [comment]
Safari 8.

76.49% availability means you leave a quarter of potential users in the dust… That's an awful lot, even without considering that most administrative users are part of the IE8 crowd.

**Comment by cbenz** [comment]
I agree

**Comment by MattiSG** [comment]
You can use http://i18next.com, or some polyfill with conditional loading if you want to stick 100% to the spec.

**Comment by cbenz** [comment]
I deployed a fix. Could you test again (since I do not have a browser without Intl, and window.Intl is not "overwriteable" in Chromium).

Or if you know a way to let me test a web application with many target browsers :)

**Comment by MattiSG** [comment]
Nope, still fails from `mixing.js:48` (`[Error] ReferenceError: Can't find variable: Intl (fonction anonyme) (main-22c1ed64567d623b6f62.js, line 3)`).

> a way to let me test a web application with many target browsers :)

Sure thing! http://saucelabs.com for scouting, and why not https://github.com/MattiSG/Watai/ for automation.

**Comment by cbenz** [comment]
Resolved, deployed and tested on a Mac
